### ISSUE TITLE
not finding cdbfasta command

### ISSUE THREAD

**Issue by catalinaguilar** [gpertea/cdbfasta#2]
Hi I have installed cdbfasta by editing the Makefile as it says there, and running 'make'. However when I try cdbfasta from the same directory it does not find the command. I didn't get any errors with I did 'make'. Is there something else I am missing? Not sure what could be the problem.

Thanks,
Catalina

**Comment by gpertea** [comment]
I guess you know that on Unix-like systems (Linux, OSX) the current path is *not* automatically added to the current shell's executable search path.. That only happens on Windows. 
You can check that the executable was indeed built properly (`ls -l cdbfasta`) and you can run it by specifying the path to the program (e.g. using the `./cdbfasta` command instead of plain `cdbfasta`) *or*, more generally, by copying the executable in any of the directories in your $PATH (`echo $PATH` should show you a list of those directories).

**Comment by catalinaguilar** [comment]
Hi thanks for your reply. Yes it is Linux system,  I tried using ./cdbfasta and it works, I was able to retrieve the fasta sequences I needed.
